name: Acceptance Tests
on:
  release:
    types: [published]
  schedule:
    - cron: "0 13 * * *"
jobs:
  test:
    name: Matrix Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        unifi_version:
          - "latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      # Pre-install Teraform, so that test cases don't try installing their temporary copy
      # See https://github.com/hashicorp/terraform-plugin-testing/issues/429
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false

      # The acceptance tests sometimes timeout for some unknown reason.
      - name: TF acceptance tests
        uses: "nick-fields/retry@v3"
        with:
          timeout_minutes: 20
          max_attempts: 3
          command: make testacc TEST_TIMEOUT=1h UNIFI_STDOUT=true UNIFI_VERSION=${{ matrix.unifi_download_url && 'beta' || matrix.unifi_version }} UNIFI_DOWNLOAD_URL=${{ matrix.unifi_download_url }}
          retry_on: "timeout"